FROM node:20

WORKDIR /app/apps/storefront-ui

# Install dependencies
COPY apps/storefront-ui/package.json ./
RUN npm install

# For dev, source code will be mounted as a volume, so no need to copy it here

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]