export const NODE_ENV = 'NODE_ENV';
export const SERVER_HTTP_PORT = 'SERVER_HTTP_PORT';

export const COGNITO_REGION = 'COGNITO_REGION';
export const COGNITO_ENDPOINT = 'COGNITO_ENDPOINT';
export const COGNITO_USER_POOL_ID = 'COGNITO_USER_POOL_ID';
export const COGNITO_CLIENT_ID = 'COGNITO_CLIENT_ID';

export const AWS_REGION = 'AWS_REGION';
export const AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID';
export const AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY';

export const POSTGRES_HOST = 'POSTGRES_HOST';
export const POSTGRES_PORT = 'POSTGRES_PORT';
export const POSTGRES_USER = 'POSTGRES_USER';
export const POSTGRES_PASSWORD = 'POSTGRES_PASSWORD';
export const POSTGRES_DB = 'POSTGRES_DB';
