FROM node:20

WORKDIR /app/cms-ui

# Install dependencies
COPY apps/cms-ui/package.json ./
RUN npm install

# For dev, source code will be mounted as a volume, so no need to copy it here

EXPOSE 5174

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]